[package]
name = "wlh2ipawlh"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
itertools = "0.10"
triple_accel = "*"
translit = "0.5"
rapidfuzz = "0.5.0"
phf = { version = "0.11", features = ["macros"] }